name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '**.yml'

  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update local repository
        run: |
          git pull origin main

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug extracted files
        run: |
          ls -lthr /tmp/

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/compta-libremen-com:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/compta-libremen-com:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/compta-libremen-com:buildcache,mode=max 
